#!/bin/bash

# Inicia una nueva sesión de tmux llamada "my_session"
tmux new-session -d -s my_session

# Comprueba si se ha pasado un argumento
if [ -z "$1" ]; then
	# Divide la ventana en dos paneles (uno a la izquierda y otro a la derecha)
	tmux split-window -h
	tmux send-keys -t my_session:0.0 'clear' C-m
	tmux send-keys -t my_session:0.1 'clear' C-m
else
	if [ "$1" -eq 2 ]; then
		# Divide la ventana en dos paneles (uno a la izquierda y otro a la derecha)
		tmux split-window -h
		tmux send-keys -t my_session:0.0 'clear' C-m
		tmux send-keys -t my_session:0.1 'clear' C-m
	elif [ "$1" -eq 4 ]; then
		# Divide la ventana en dos paneles (uno a la izquierda y otro a la derecha)
		tmux split-window -h
		tmux split-window -h
		tmux select-pane -t 0
		tmux split-window -h
		tmux send-keys -t my_session:0.0 'clean' C-m
		tmux send-keys -t my_session:0.1 'clean' C-m
		tmux send-keys -t my_session:0.2 'clean' C-m
		tmux send-keys -t my_session:0.3 'clean' C-m
	else
		echo "El argumento proporcionado no es valido."
		tmux kill-session -t my_session
		exit 0
	fi
fi

# Sincroniza los paneles para que ambos reciban las mismas entradas
tmux setw synchronize-panes on

# Adjunta la sesión de tmux para que la puedas ver en la terminal
tmux attach-session -t my_session

# Después de salir de la sesión, mata la sesión de tmux automáticamente
tmux kill-session -t my_session
